name: 订阅

on:
    workflow_dispatch:
    schedule:
        - cron: "0 18 * * *"
    watch:
        types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: 订阅脚本 #订阅脚本
      env: 
        GHCOOKIE: ${{ secrets.GHCOOKIE }} # secrets_id 提供
      run: | 
        python DingYue.py
    - name: Commit #上传到仓库
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./Node.txt
        git commit -m "更新时间 $(date '+%Y-%m-%d %H:%M:%S')"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.TOKEN }}
         branch: main
